const projects = [
  {
    theme: "Infrastructure Réseau",
    projet: "Installation des PC sur KVM",
    date: "11/07/2024 - 12/07/2024",
    statut: "Terminé",
    logiciels: "NINITE, Windows",
  },
  {
    theme: "Infrastructure Réseau",
    projet: "Mise en place du serveur avec ArcServe",
    date: "12/07/2024",
    statut: "Terminé",
    logiciels: "ArcServe SPX, Windows Server",
  },
  {
    theme: "Cybersécurité",
    projet: "Création d'un VPN avec certificat pour accès à distance",
    date: "25/07/2024",
    statut: "Terminé",
    logiciels: "pfSense",
  },
  {
    theme: "Cybersécurité",
    projet: "Test de sécurité sur les serveurs",
    date: "17/07/2024 - 19/07/2024",
    statut: "Terminé",
    logiciels: "OCCT, AutoBackup",
  },
  {
    theme: "Support Technique",
    projet: "Intervention client Volkswagen",
    date: "01/07/2024 - 09/08/2024",
    statut: "Terminé",
    logiciels: "Windows, Firewall, VPN",
  },
  {
    theme: "Support Technique",
    projet: "Diagnostic de pannes à distance",
    date: "01/07/2024 - 09/08/2024",
    statut: "Terminé",
    logiciels: "Helper.exe, Windows",
  },
  {
    theme: "Maintenance Matériel",
    projet: "Test des disques durs serveurs S.M.A.R.T",
    date: "05/07/2024 - 06/07/2024",
    statut: "Terminé",
    logiciels: "CrystalDisk, Windows",
  },
  {
    theme: "Maintenance Matériel",
    projet: "Changement de pâte thermique CPU/GPU",
    date: "17/07/2024 - 19/07/2024",
    statut: "Terminé",
    logiciels: "OCCT",
  },
  {
    theme: "Maintenance Matériel",
    projet: "Ajout de RAM et initialisation de PC",
    date: "01/07/2024 - 09/08/2024",
    statut: "Terminé",
    logiciels: "Windows",
  },
  {
    theme: "Documentation Technique",
    projet: "Rédaction de la documentation pour la reprise d'activité",
    date: "08/07/2024 - 09/08/2024",
    statut: "Terminé",
    logiciels: "Google Docs, Office",
  },
  {
    theme: "Documentation Technique",
    projet: "Mise à jour de la documentation technique ArcServe",
    date: "08/07/2024 - 09/08/2024",
    statut: "Terminé",
    logiciels: "ArcServe SPX, Office, Google Docs",
  },
  {
    theme: "Formation",
    projet: "Préparation à la certification ArcServe SPX",
    date: "01/07/2024 - Aujourd'hui",
    statut: "En cours",
    logiciels: "ArcServe SPX",
  },
  {
    theme: "Maintenance Matériel",
    projet:
      "Récupération de vieux PC pour association avec test et réinstallation Windows 10/11",
    date: "25/07/2024 - 09/08/2024",
    statut: "Terminé",
    logiciels: "Windows",
  },
  {
    theme: "Infrastructure Réseau",
    projet: "Création de clés bootables Win 10 / 11 / srv 2022",
    date: "10/07/2024",
    statut: "Terminé",
    logiciels: "Windows",
  },
  {
    theme: "Support Technique",
    projet: "Analyse des logs suite à des pertes de connexion",
    date: "26/07/2024",
    statut: "Terminé",
    logiciels: "SSMS, Windows",
  },
  {
    theme: "Support Technique",
    projet: "Déballage de commandes et ajout de RAM",
    date: "01/07/2024 - 09/08/2024",
    statut: "Terminé",
    logiciels: "Windows",
  },
];

export default projects;
